DataConfig:
    valid_label: 1
    anomaly_label: 3
    contamination: 0.01
    test_size: 0.2
    random_state: 42

DeepSwarm:
    save_folder:
    metrics: accuracy
    max_depth: 3 # Autoencoder
    min_depth: 1 #Autoencoder without middle latent space
    reuse_patience: 1

    aco:
        pheromone:
            start: 0.1
            decay: 0.1
            evaporation: 0.1
            verbose: 1
        greediness: 0.5
        ant_count: 10
        latent_dim: 16 # latent space (center of Autoencoder)

    anomaly:
        quantile: 0.99

    backend:
        epochs: 20
        batch_size: 128
        patience: 5
        verbose: 1
        optimizer: adam
        loss: binary_crossentropy # Output at the end is in binary

Nodes:

    InputNode:
        type: Input
        attributes:
            shape: [!!python/tuple [28, 28, 1]]
        transitions:
            DenseNode: 1.0

    InputDecoderNode:
        type: Input
        attributes:
            shape: [ !!python/tuple [ 14 ] ]
        transitions:
            DenseNode: 1.0

    FlattenNode:
        type: Flatten
        attributes: { }
        transitions:
            DenseNode: 1.0

    ReShapeNode:
        type: Reshape
        attributes:
            target_shape: [ !!python/tuple [ 7, 7, 1 ] ]
        transitions:
            DenseNode: 1.0

    DenseNode:
        type: Dense
        attributes:
            output_size: [128, 64, 32, 16, 8, 4, 2]
            activation: [ReLU]
        transitions:
            DenseNode: 1.0

    OutputNode:
        type: Output
        attributes:
            output_size: [1]
            activation: [Sigmoid]
        transitions: {}