DataConfig:
    valid_label: [1,2,3,4,5,6,7,8,9]
    anomaly_label: [0]
    contamination: 0.01
    test_size: 0.2
    random_state: 42

DeepSwarm:
    save_folder:
    metrics: accuracy
    #Autoencoder depth without middle latent space
    max_depth: 4
    min_depth: 3
    reuse_patience: 1

    aco:
        pheromone:
            start: 0.1
            decay: 0.1
            evaporation: 0.1
            verbose: 1
        greediness: 0.50
        ant_count: 16
        latent_dim: 16 # latent space (center of Autoencoder)

    # Finding the best balance between TP anomalies and FN instances with quantile size is all the magic for success
    anomaly:
        quantile: 0.98

    backend:
        epochs: 5
        batch_size: 32
        patience: 5
        verbose: 1
        optimizer: adam
        loss: binary_crossentropy # Output at the end is in binary

Nodes:

    InputNode:
        type: Input
        attributes:
            shape: [!!python/tuple [28, 28, 1]]
        transitions:
            DenseNode: 1.0

    InputDecoderNode:
        type: Input
        attributes:
            shape: [ !!python/tuple [ 14 ] ]
        transitions:
            DenseNode: 1.0

    FlattenNode:
        type: Flatten
        attributes: { }
        transitions:
            DenseNode: 1.0

    ReShapeNode:
        type: Reshape
        attributes:
            target_shape: [ !!python/tuple [ 7, 7, 1 ] ]
        transitions:
            DenseNode: 1.0

    DenseNode:
        type: Dense
        attributes:
            output_size: [128, 64, 32, 16, 8, 4, 2]
            activation: [ReLU, LeakyReLU,Tanh]
        transitions:
            DenseNode: 1.0

    OutputNode:
        type: Output
        attributes:
            output_size: [1]
            activation: [Sigmoid]
        transitions: {}